Exploring the data sets using different tools and technique  to desire insights from the data sets using data mining, Ml algorithm, Deep learning.

Data is collection of facts, numbers, words,measurements,observations.data comes from different sources like images,videos,texts,etc.
data are structured and unstructured .
data are raw facts which have 2 different types be qualititive is description  or quantitive is numerical.
qualititive data:"hello how are you"
quantitve which is 2 types. discrete which is countable and continuous which is measureable.

MEASURE OF CENTRAL .

*   mean
*   median
*   node






In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


mean

In [ ]:
x=np.array([10,20,30,40,50])
total=np.sum(x)
total

150

In [ ]:
avg_val=total/len(x)
avg_val

30.0

In [ ]:
mean_val=np.mean(x)
print("average:",mean_val)

average: 30.0


In [ ]:
age=np.array([16,17,15,18,19,16,15,16])
avg_age=np.mean(age)
avg_age

16.5

In [ ]:
#avg not working on this case
income=np.array([10000,15000,20000,18000,17000,1000000])

In [ ]:
avg_income=np.mean(income)
print("avg_income:",avg_income)

avg_income: 180000.0


In [ ]:
#For resolving above proble of outliers, we have to  use median instead of mean
x=np.array([10,9,11,13,15,18,21,20])
x.sort()


In [ ]:
median=(len(x)+1)/2
median


4.5

In [ ]:
x[int(median)]

15

In [ ]:
median=int((len(x)+1)/2)
# median.sort()

In [ ]:
print("the median value:",median)

the median value: 4


In [ ]:
x=np.array([10,9,11,13,15,18,20,21,22])
x

array([10,  9, 11, 13, 15, 18, 20, 21, 22])

Below is for even

In [ ]:
mid1=int((len(x)+1)/2)
mid1

5

In [ ]:
mid2=int(np.ceil(len(x)+1)/2)
mid2

5

In [ ]:
median=np.median([x[mid1],x[mid2]])
median

18.0

In [ ]:
median_val=np.median(x)
median_val

15.0

In [ ]:
median_val2=np.median(median)
median_val2

18.0

In [ ]:
income=np.array([10000,15000,20000,18000,17000,1000000])
np.mean(income)

180000.0

In [ ]:
# median use for searchine central value which provide us a more accurate value
np.median(income)

17500.0

MODE

In [ ]:
from scipy import stats

In [ ]:
a=np.random.randint(1,10,50)
a

array([3, 9, 5, 3, 2, 8, 1, 2, 8, 3, 4, 6, 8, 4, 7, 2, 5, 8, 3, 5, 8, 9,
       7, 7, 6, 8, 1, 7, 1, 3, 9, 3, 9, 3, 1, 1, 5, 7, 3, 9, 1, 3, 9, 5,
       6, 5, 2, 9, 2, 5])

In [ ]:
m=stats.mode(a)
m

ModeResult(mode=array([3]), count=array([9]))

In [ ]:
m[0]

array([3])

In [ ]:
m[1]

array([9])

OUTLIERS
they can change the mean a lot , so we ca can either not use  or use the median or mode instead. we exploring more by using quartile

In [ ]:
income=np.array([10000,15000,20000,18000,17000,1000000])

Meadurement of spread:


how data sets are distributed

1.   range
2.   quartile
1.   variance
2.   standard derivation





RANGE

In [ ]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
low=a.min()
low

1

In [ ]:
high=a.max()
high

9

In [ ]:
rng=high-low
print(rng)

8


In [ ]:
a1=np.array([2,7,8,10,20])
a1

array([ 2,  7,  8, 10, 20])

In [ ]:
high=a1.min()

In [ ]:
low=a1.max()

In [ ]:
rng1=high-low

In [ ]:
a1=np.array([2,7,8,10,20,10000])
a1

array([    2,     7,     8,    10,    20, 10000])

In [ ]:
high=a1.max()
low=a1.min()

In [ ]:
rng=high-low
rng

9998

STANDARD DEVIATION


HOW SPREAD OUT NUMBERS ARE

VARIANCE

In [ ]:
heights=np.array([600,470,170,430,300])
mu=np.mean(heights)
print(mu)

394.0


In [ ]:
res=(heights-mu)
res

array([ 206.,   76., -224.,   36.,  -94.])

In [ ]:
res1=np.square(res)
res1

array([42436.,  5776., 50176.,  1296.,  8836.])

In [ ]:
var=np.mean(res1)
var

21704.0

STANDARD DEVIATIOn which  is square of VARIANCE

In [ ]:
std=np.sqrt(var)
std

147.32277488562318

STD  calculation using NumPy

In [ ]:
np.var(heights)

21704.0

In [ ]:
np.std(heights)

147.32277488562318